lang: fr

resources: CNAME

project:
  type: website

website:
  title: "Niviuk Naktuk"
  site-url: "https://parapente.nicolasbressoud.ch"
  favicon: "img/favicon.ico"
  navbar:
    right:
      - href: about.qmd
        text: "A propos"
      - icon: github
        href: https://github.com/bresnico
      - icon: twitter
        href: https://twitter.com/NBressoud
format:
  html:
    theme: cosmo
    css: styles.css



