project:
  type: website

website:
  title: "parapente-suivi"
  site-url: "https://parapente.nicolasbressoud.ch"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



